name: fuel_monitor
description: A Flutter app for monitoring fuel prices.

# Указываем версию SDK для Dart
environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # Управление состоянием (по рекомендации)
  dio: ^5.4.0 # HTTP-клиент для API
  shared_preferences: ^2.2.2 # Хранение настроек
  intl: ^0.19.0 # Локализация
  firebase_messaging: ^14.7.10 # Пуш-уведомления (добавим позже)
  http: ^0.13.3 # HTTP-запросы
